### ISSUE TITLE
Does not comply with Thunderstore format

### ISSUE THREAD

**Issue by laundmo** [Strykus/CustomScopeFOV#1]
# Does not comply with Thunderstore format

Thunderstore link: https://northstar.thunderstore.io/package/Avalar/CustomScopeFOV/

This mod does not comply with the Thunderstore format and will therefore fail to install when using a mod manager.

Please refer to this guide for the correct format https://r2northstar.gitbook.io/r2northstar-wiki/modding-and-development/modding/publishing

Or alternatively take a look at this example repository: https://github.com/laundmo/northstar-mod-template

**Comment by Strykus** [comment]
Fixed it
